### PR TITLE
Sundials 5.x port

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
Hello @modelonrobinandersson I had to recreate the PR has the branch was out of sync.
I added the changelog entry.
I also noticed the files mixed unix and windows line endings, now everything is LF.

**Comment by modelonrobinandersson** [comment]
Thank you @jschueller

**Comment by jschueller** [comment]
@modelonrobinandersson is there a new version planned ?

**Comment by PeterMeisrimelModelon** [comment]
We are planning a new release this month.

**Pull request merged**
